name: dep_gen
description: An annotation processor for generation of methods dependencies.
version: 1.0.0
# homepage: https://github.com/jorgecoca/todo_reporter.dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
#  build: ^2.0.0
#  source_gen: ^1.0.0
  analyzer: ^4.0.0
  args: ^2.3.1
  path: ^1.8.1
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
#  build_test: ^2.1.5
#  build_runner: ^2.0.0
#  test: ^1.16.0

