name: dep_gen
description: This package allows to implement dependency injection in a project.
version: 1.1.6
homepage: https://github.com/dadrum/dep_gen.git

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ^6.7.0
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0

