name: dep_gen
description: Generates methods for creating instances of classes with automatic dependency substitution.
version: 1.0.15
homepage: https://github.com/dadrum/dep_gen.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  args: ^2.4.2
  path: ^1.8.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1

