name: dep_gen
description: This package allows to implement dependency injection in a project.
version: 1.1.7
homepage: https://github.com/dadrum/dep_gen.git

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ^6.11.0
  args: ^2.6.0
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1

